import type { ProviderDefinition } from '../../types/provider';

export const PROVIDER_DEFINITIONS: ProviderDefinition[] = [
  // ==================== TIER 1 ====================
  {
    id: 'groq',
    name: 'Groq',
    description: 'Ultra-fast LPU inference engine for open-source models',
    apiType: 'openai-compatible',
    baseUrl: 'https://api.groq.com/openai/v1',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    keyPatterns: [/^gsk_[a-zA-Z0-9]{48,}$/],
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'llama-3.3-70b-versatile',
    docsUrl: 'https://console.groq.com/docs',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 1,
  },
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'GPT-4o, o1, and general chat intelligence',
    apiType: 'openai-native',
    baseUrl: 'https://api.openai.com/v1',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    keyPatterns: [
      /^sk-proj-[a-zA-Z0-9_-]{40,}$/,
      /^sk-admin-[a-zA-Z0-9_-]{40,}$/,
      /^sk-[a-zA-Z0-9]{48,}$/
    ],
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'gpt-4o',
    docsUrl: 'https://platform.openai.com/docs',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 1,
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    description: 'Multimodal Gemini models with large context windows',
    apiType: 'gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    chatEndpoint: '/models',
    modelsEndpoint: '/models',
    keyPatterns: [/^AIzaSy[0-9A-Za-z_-]{33}$/],
    authHeader: 'x-goog-api-key',
    authPrefix: '',
    defaultModelId: 'gemini-1.5-flash',
    docsUrl: 'https://ai.google.dev/docs',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 1,
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    description: 'Claude 3.5 Sonnet, Claude 3.5 Haiku, and Claude Opus',
    apiType: 'anthropic',
    baseUrl: 'https://api.anthropic.com/v1',
    chatEndpoint: '/messages',
    modelsEndpoint: '/models',
    keyPatterns: [
      /^sk-ant-api03-[a-zA-Z0-9_-]{40,}$/,
      /^sk-ant-[a-zA-Z0-9_-]{30,}$/
    ],
    authHeader: 'x-api-key',
    authPrefix: '',
    defaultModelId: 'claude-3-5-sonnet-20241022',
    headers: {
      'anthropic-version': '2023-06-01',
      'anthropic-dangerous-direct-browser-access': 'true'
    },
    docsUrl: 'https://docs.anthropic.com',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 1,
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    description: 'Unified gateway to 200+ models with universal fallback',
    apiType: 'openai-compatible',
    baseUrl: 'https://openrouter.ai/api/v1',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    keyPatterns: [/^sk-or-v1-[a-f0-9]{64}$/],
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'meta-llama/llama-3.3-70b-instruct',
    headers: {
      'HTTP-Referer': 'https://arh.ai',
      'X-Title': 'ARH Playground'
    },
    docsUrl: 'https://openrouter.ai/docs',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 1,
  },
  {
    id: 'nvidia',
    name: 'NVIDIA NIM',
    description: 'Hardware-accelerated AI enterprise models',
    apiType: 'openai-compatible',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    keyPatterns: [/^nvapi-[A-Za-z0-9_-]{30,}$/],
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'meta/llama-3.2-11b-vision-instruct',
    docsUrl: 'https://build.nvidia.com',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 1,
  },
  {
    id: 'together',
    name: 'Together AI',
    description: 'Fast cloud inference for open-source AI models',
    apiType: 'openai-compatible',
    baseUrl: 'https://api.together.xyz/v1',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    keyPatterns: [/^[a-f0-9]{64}$/],
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo',
    docsUrl: 'https://docs.together.ai',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 1,
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    description: 'Wafer-Scale engine for lightning inference speeds',
    apiType: 'openai-compatible',
    baseUrl: 'https://api.cerebras.ai/v1',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    keyPatterns: [/^csk-[a-zA-Z0-9]{32,}$/],
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'llama-3.3-70b',
    docsUrl: 'https://inference-docs.cerebras.ai',
    supportsStreaming: true,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 1,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    description: 'High performance DeepSeek-V3 and DeepSeek-R1 reasoning models',
    apiType: 'openai-compatible',
    baseUrl: 'https://api.deepseek.com',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    keyPatterns: [/^sk-[a-f0-9]{32}$/],
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'deepseek-chat',
    docsUrl: 'https://platform.deepseek.com/docs',
    supportsStreaming: true,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 1,
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    description: 'Mistral Large, Codestral, and Pixtral models',
    apiType: 'openai-compatible',
    baseUrl: 'https://api.mistral.ai/v1',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    keyPatterns: [/^[a-zA-Z0-9]{32}$/],
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'mistral-large-latest',
    docsUrl: 'https://docs.mistral.ai',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 1,
  },

  // ==================== TIER 2 ====================
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    description: 'Optimized serverless AI inference platform',
    apiType: 'openai-compatible',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    keyPatterns: [/^fw_[a-zA-Z0-9]{32,}$/],
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'accounts/fireworks/models/llama-v3p3-70b-instruct',
    docsUrl: 'https://docs.fireworks.ai',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 2,
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    description: 'Search-augmented reasoning and online sonar models',
    apiType: 'openai-compatible',
    baseUrl: 'https://api.perplexity.ai',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '',
    keyPatterns: [/^pplx-[a-f0-9]{48,}$/],
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'sonar-pro',
    docsUrl: 'https://docs.perplexity.ai',
    supportsStreaming: true,
    supportsVision: false,
    supportsTools: false,
    supportsJsonMode: true,
    tier: 2,
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    description: 'Grok 2 and multimodal reasoning by xAI',
    apiType: 'openai-compatible',
    baseUrl: 'https://api.x.ai/v1',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    keyPatterns: [/^xai-[a-zA-Z0-9]{40,}$/],
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'grok-2-latest',
    docsUrl: 'https://docs.x.ai',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 2,
  },
  {
    id: 'cohere',
    name: 'Cohere',
    description: 'Command R+ enterprise models for reasoning and retrieval',
    apiType: 'openai-compatible',
    baseUrl: 'https://api.cohere.com/v2',
    chatEndpoint: '/chat',
    modelsEndpoint: '/models',
    keyPatterns: [/^[a-zA-Z0-9_-]{40}$/],
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'command-r-plus-08-2024',
    docsUrl: 'https://docs.cohere.com',
    supportsStreaming: true,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 2,
  },
  {
    id: 'sambanova',
    name: 'SambaNova',
    description: 'High-speed SN40L Reconfigurable Dataflow Unit',
    apiType: 'openai-compatible',
    baseUrl: 'https://api.sambanova.ai/v1',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'Meta-Llama-3.3-70B-Instruct',
    docsUrl: 'https://community.sambanova.ai',
    supportsStreaming: true,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 2,
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    description: 'Hugging Face serverless inference endpoints',
    apiType: 'openai-compatible',
    baseUrl: 'https://api-inference.huggingface.co/v1',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    keyPatterns: [/^hf_[a-zA-Z0-9]{34,}$/],
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'meta-llama/Llama-3.2-3B-Instruct',
    docsUrl: 'https://huggingface.co/docs/api-inference',
    supportsStreaming: true,
    supportsVision: false,
    supportsTools: false,
    supportsJsonMode: false,
    tier: 2,
  },
  {
    id: 'deepinfra',
    name: 'DeepInfra',
    description: 'Pay-as-you-go serverless models at low cost',
    apiType: 'openai-compatible',
    baseUrl: 'https://api.deepinfra.com/v1/openai',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'meta-llama/Meta-Llama-3.1-70B-Instruct',
    docsUrl: 'https://deepinfra.com/docs',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 2,
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow',
    description: 'Fast cloud models and multimodal Qwen inference',
    apiType: 'openai-compatible',
    baseUrl: 'https://api.siliconflow.cn/v1',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'Qwen/Qwen2.5-72B-Instruct',
    docsUrl: 'https://docs.siliconflow.cn',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 2,
  },
  {
    id: 'moonshot',
    name: 'Moonshot / Kimi',
    description: 'Moonshot AI large context window chat models',
    apiType: 'openai-compatible',
    baseUrl: 'https://api.moonshot.cn/v1',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'moonshot-v1-8k',
    docsUrl: 'https://platform.moonshot.cn/docs',
    supportsStreaming: true,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 2,
  },
  {
    id: 'qwen',
    name: 'Alibaba DashScope (Qwen)',
    description: 'Qwen 2.5 foundation models via OpenAI compatible gateway',
    apiType: 'openai-compatible',
    baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'qwen-plus',
    docsUrl: 'https://help.aliyun.com/zh/model-studio',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 2,
  },
  {
    id: 'nebius',
    name: 'Nebius AI Studio',
    description: 'GPU infrastructure and AI cloud inference',
    apiType: 'openai-compatible',
    baseUrl: 'https://api.studio.nebius.ai/v1',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'meta-llama/Meta-Llama-3.1-70B-Instruct',
    docsUrl: 'https://docs.nebius.com',
    supportsStreaming: true,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 2,
  },
  {
    id: 'experiential',
    name: 'Experiential Labs',
    description: 'Unified AI gateway providing high-speed access to frontier and open-source models',
    apiType: 'openai-compatible',
    baseUrl: 'https://api.experientiallabs.ai/v1',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    keyPatterns: [/^xpl_[a-f0-9]{40}$/i, /^xpl_[a-zA-Z0-9_-]{10,}$/],
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'meta-llama/llama-3.3-70b-instruct',
    docsUrl: 'https://platform.experientiallabs.ai/docs',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 2,
  },
  {
    id: 'token-router',
    name: 'Token Router',
    description: 'OpenAI-compatible AI gateway routing inference across a distributed network of GPU providers',
    apiType: 'openai-compatible',
    baseUrl: 'https://beta.token-router.org/v1',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    keyPatterns: [/^vk_live_[A-Za-z0-9_-]+$/],
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'qwen3.6-27b',
    docsUrl: 'https://docs.token-router.org/',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 2,
  },
  {
    id: 'bazaarlink',
    name: 'BazaarLink',
    description: 'Unified OpenAI-compatible AI gateway providing access to multiple AI model providers through one API',
    apiType: 'openai-compatible',
    baseUrl: 'https://api.bazaarlink.ai/v1',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    keyPatterns: [/^sk-bl-[A-Za-z0-9_-]+$/],
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'auto',
    docsUrl: 'https://bazaarlink.ai/en/docs',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 2,
  },
  {
    id: 'nrouter',
    name: 'NRouter',
    description: 'Enterprise-grade LLM gateway with smart model routing, AI guardrails, and budget management',
    apiType: 'openai-compatible',
    baseUrl: 'https://api.nrouter.ai/v1',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    keyPatterns: [/^sk-nrouter-[A-Za-z0-9_-]+$/],
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    defaultModelId: 'openai/gpt-4o',
    docsUrl: 'https://nrouter.ai/docs',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 2,
  },
  {
    id: 'custom',
    name: 'Custom Provider',
    description: 'Connect to any OpenAI-compatible API or local server (Ollama, vLLM, LM Studio)',
    apiType: 'custom',
    baseUrl: '',
    chatEndpoint: '/chat/completions',
    modelsEndpoint: '/models',
    authHeader: 'Authorization',
    authPrefix: 'Bearer',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    tier: 2,
  }
];
